linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 12
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3

linters:
  enable-all: true
  disable:
    - maligned
    - goimports
    - depguard
    - dupl
    - interfacer
